version: 0.2

env:
  variables:
    NG_CLI_ANALYTICS: "ci"
    AWS_DEFAULT_REGION: "eu-west-1"
    AWS_ACCOUNT_ID: 178276444724
    IMAGE_REPO_NAME: bitfex/frontend-user

phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
      - $(aws ecr get-login --no-include-email --region eu-west-1)
      - export IMAGE_TAG=$(date +%F)
  build:
    commands:
      - echo Build started on `date`
      - sed 's@http://52.211.112.45/api/v1/@https://staging-stigasoft-backend-admin.bitfex.com/api/v1/@g' src/assets/config/config.dev.json
      - sed 's@http://52.211.112.45/api/v1/@https://staging-stigasoft-backend-admin.bitfex.com/api/v1/@g' src/assets/config/config.prod.json
      - npm run-script build_prod
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG . -f Dockerfile.nginx
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `data`
      - echo push latest Docker images to ECR...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG